---
title: "Beispiel parametrisierte Kurve in Python mit Matplotlib"
format: html
embed-resources: true
jupyter: python3
---

Die üblichen Importe, um Schaubilder erstellen zu können:
```{python}
import matplotlib.pyplot as plt
import numpy as np
```

Es ist guter Programmierstil, konstante Zahlenwerte am Anfang als Variablen zu definieren:
```{python}
y0 = 15  # Abwurfhöhe
v0 = 10  # Abwurfgeschwindigkeit
g = 9.81  # Erdbeschleunigung
```

Die Berechnung von $x(t)$ und $y(t)$ ist einfach, wird aber voraussichtlich an mehreren Stellen benötigt. Daher ist es sinnvoll, die Berechnungen in Funktionen auszulagern:
```{python}
def x(t):
    return v0 * t

def y(t):
    return y0 - 1/2 * g * t**2
```

### a)
Grafische Darstellung der Bahnkurve:
```{python}
x_werte = [x(t) for t in np.linspace(0,2,100)]
y_werte = [y(t) for t in np.linspace(0,2,100)]

plt.plot(x_werte, y_werte)
plt.grid()
plt.axis("equal")
plt.show()
```

### b)
Es wird über eine While-Schleife $t$ in kleinen Schritten erhöht, bis $y(t)$ negativ wird:
```{python}
t = 0
dt = 0.01  # Zeitschrittweite
while y(t) >= 0:
    t += dt

print(f"Zeit bis zum Aufprall: {t:.2f} s")
```

### c)
Die horizontale Wurfweite wird mit der Funktion `x(t)` bekommt man mit der vorherigen Teilaufgabe praktisch mitgeliefert. Wir haben ja schon den Zeitpunkt, d.h. wir müssen lediglich noch die dazu gehörige $x$-Koordinate berechnen:
```{python}
print(f"Horizontale Wurfweite: {x(t):.2f} m")
```

### d)
Bei der gegebenen Anfangsgeschwindigkeit ist die Wurfweite größer als 12 m. Die Idee ist, die Anfangsgeschwindigkeit so lange in kleinen Schrittten zu verringern, bis die Wurfweite gerade noch 12 m beträgt. Um den Code übersichtlich zu halten, empfiehlt es sich, die Berechnung der Wurfweite in eine eigene Funktion auszulagern:
```{python}
def wurfweite():
    t = 0
    dt = 0.01
    while y(t) >= 0:
        t += dt
    return x(t)
```

Nun können wir wie beschrieben $v_0$ so lange verringern, bis die gewünschte Wurfweite von 12 m erreicht ist:
```{python}
v0 = 10  # Haben wir eigentlich schon, nur zur Erinnerung :)
ziel_wurfweite = 12
dv = 0.01  # Schrittweite für die Verringerung der Anfangsgesch

while wurfweite() > ziel_wurfweite:
    v0 -= dv

print(f"Anfangsgeschwindigkeit für Wurfweite von 12 m: {v0:.2f} m/s")
```

### Das ganze Programm
```{python}
import matplotlib.pyplot as plt
import numpy as np

y0 = 15  # Abwurfhöhe
v0 = 10  # Abwurfgeschwindigkeit
g = 9.81  # Erdbeschleunigung

def x(t):
    return v0 * t

def y(t):
    return y0 - 1/2 * g * t**2

# a)
x_werte = [x(t) for t in np.linspace(0,2,100)]
y_werte = [y(t) for t in np.linspace(0,2,100)]

plt.plot(x_werte, y_werte)
plt.grid()
plt.axis("equal")
plt.show()

# b)
t = 0
dt = 0.01  # Zeitschrittweite
while y(t) >= 0:
    t += dt

print(f"Zeit bis zum Aufprall: {t:.2f} s")

# c)
def wurfweite():
    t = 0
    dt = 0.01
    while y(t) >= 0:
        t += dt
    return x(t)

print(f"Horizontale Wurfweite: {wurfweite():.2f} m")

# d)
ziel_wurfweite = 12
dv = 0.01  # Schrittweite für die Verringerung der Anfangsgesch

while wurfweite() > ziel_wurfweite:
    v0 -= dv

print(f"Anfangsgeschwindigkeit für Wurfweite von 12 m: {v0:.2f} m/s")
```


